### ISSUE TITLE
Mind helping me setup this code collection to work on discord?

### ISSUE THREAD

**Issue by ToasterGen** [hanaui-git/ZeroDiscord#11]
Basically, Here's the deal, I'm a novice discord bot creator and I need someone to record some instructions to follow, 
the reason why I'm asking is that if people that don't do coding look at the README.md file in the NuclearNuke folder, 
they'll be confused and ask where do I start, what do I do to make this work, or how do I make the bot work with ZeroDiscord?

so if you could make an instructional video on how to setup a discord bot for ZeroDiscord to work, I would highly appreciate it,

anyways, I don't want to take up most of your time, so... have a great day,

**Comment by I2rys** [comment]
Hello @ToasterGen,
I understand what your problem is but I'm afraid I can't make a video because my PC does not work properly when recording, perhaps do you have any accounts in platforms like Discord, Revolt & etc so I can assist you there?
