### ISSUE TITLE
It seems like you don't have Discord installed in your PC.

### ISSUE THREAD

**Issue by Cheezecan** [hanaui-git/ZeroDiscord#12]
im trying to use the discord token protector but its not working
it shows It seems like you don't have Discord installed in your PC in terminal

**Comment by I2rys** [comment]
Hello @Cheezecan,
I'm afraid the Discord token protector is for PC only and It's no longer working after the new update of Discord. Sorry for the inconvenience also because I forgot to update the README.

**Comment by Cheezecan** [comment]
Could you edit the README file to show what works on macOS and/or windows please?

**Comment by I2rys** [comment]
> Could you edit the README file to show what works on macOS and/or windows please?

Sure. :)
