### ISSUE TITLE
How do you setup?

### ISSUE THREAD

**Issue by FailedCoder23** [hanaui-git/ZeroDiscord#17]
How do you use this?

**Comment by I2rys** [comment]
Hello @FailedCoder23,
This is how I use it:
1. Clone this repository
2. Make a file called "index.js" in ZeroDiscord root directory and open CMD on it
3. Run "npm init" then "npm i discord.js@12.5.3"
4. After that, just check the README of a tool that you want to use and run the "Installation" command

I recommend you to use **NodeJS V14.20.0**.

**Comment by Breadmasterpro** [comment]
Hi, I’m not very experienced when it comes to files and modding, could you please make some sort of video or detailed guide to explain it? Thankyou!

**Comment by I2rys** [comment]
> Hi, I’m not very experienced when it comes to files and modding, could you please make some sort of video or detailed guide to explain it? Thankyou!

Hello! By any chance, do you have a Discord?

**Comment by iskrusSUS** [comment]
> > Hi, I’m not very experienced when it comes to files and modding, could you please make some sort of video or detailed guide to explain it? Thankyou!
> 
> Hello! By any chance, do you have a Discord?

Hey can you help me set it up please? Here is my discord: Tomato#7440

**Comment by FergalHennessy** [comment]
> > > Hi, I’m not very experienced when it comes to files and modding, could you please make some sort of video or detailed guide to explain it? Thankyou!
> > 
> > 
> > Hello! By any chance, do you have a Discord?
> 
> Hey can you help me set it up please? Here is my discord: Tomato#7440

hey iskrus, did you ever get it to work? can you add me on discord serendipity#6824

**Comment by I2rys** [comment]
Hello @FergalHennessy I have added you in Discord.

**Comment by FergalHennessy** [comment]
> 

fixed, ty @l2rys
