### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by YeetingForLife** [hanaui-git/ZeroDiscord#9]
I was trying to use the token generator but this error stop the program. I am not very good at js so please help.

**Comment by I2rys** [comment]
Hello @YeetingForLife,
Sorry to keep you waiting a lot because I didn't saw this issue, I think the issue on this one is that you installed the latest version of chalk which is for TS only.

Run this command to fix the problem:
```
npm uninstall chalk && npm i chalk@2.4.2
```
